name: Test
on:
- pull_request

jobs:
  test:
    strategy:
      matrix:
        go:
        - '1.17.x'
        - '1.18.x'
        - '1.19.x'
        - '1.20.x'
        - '1.21.x'

    runs-on: ubuntu-latest-large

    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4

    - name: Setup Go ${{ matrix.go }}
      uses: actions/setup-go@7b8cf10d4e4a01d4992d18a89f4d7dc5a3e6d6f4  # v4
      with:
        go-version: ${{ matrix.go }}

    - name: Download Dependencies
      run: go mod download

    - name: Run Tests
      run: |
        make vendor
        make test
